### ISSUE TITLE
Using attribute mutator

### ISSUE THREAD

**Issue by Cannonb4ll** [EscapeWork/laravel-translations#5]
I am using your package, and wanting to use your mutator example as well:

```
    public function getTitleAttribute()
    {
        return $this->translations->_get('title');
    }
```

Problem is that my model will only return a title when a translation has been created, and not when its present in the original model. How to solve?

**Comment by luisdalmolin** [comment]
So do you have a `title` field on your model also?

Maybe you can do something like that:

```php
public function getTitleAttribute()
{
    return $this->translations->_get('title') ?: $this->attributes['title'];
}
```

**Comment by Cannonb4ll** [comment]
Hero.
